"""change embedding dimension to 768

Revision ID: 383bbab17eeb
Revises: 3506f9978118
Create Date: 2026-04-17 21:58:25.871610

"""
# pyright: reportAttributeAccessIssue=false
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector  # noqa: F401
import sqlmodel  # Required for SQLModel types like AutoString


# revision identifiers, used by Alembic.
revision: str = '383bbab17eeb'
down_revision: Union[str, Sequence[str], None] = '3506f9978118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clear old 384d embeddings before changing column dimension
    op.execute("UPDATE chunks SET embedding = NULL")
    op.alter_column('chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###
